### ISSUE TITLE
Do you have plans to release the code for dataset collection?

### ISSUE THREAD

**Issue by makolon** [NVlabs/Optimus#3]
Hi, thank you for sharing your excellent implementation!
I believe you are using PDDLStream to collect datasets on Robosuite, and I understand that the original implementation of PDDLStream heavily relies on the PyBullet API.
Did you modify PDDLStream specifically for Robosuite (MuJoCo), or did you employ a different approach to collect the dataset? Also, do you have any plans to release the implementation for dataset collection?
I have implemented a similar setup where I plan trajectories using PDDLStream on PyBullet, save the planned trajectories, and render them in IsaacSim. I'm curious to know if our implementations are similar.
Thank you.

**Comment by mihdalal** [comment]
Hi, thank you for your interest in our work, and apologies for the late reply.
We did not modify PDDLStream specifically for MuJoCo - instead you can simply write a wrapper that copies the states, objects and environment to PyBullet, perform planning in PDDLStream there, and then copy over the states back to your original MuJoCo environment. I think this is similar to the setup you are describing. 
We will not be releasing the dataset collection implementation unfortunately but it should be possible to replicate our effort using the approach I described above. Let me know if you have further questions!

**Comment by makolon** [comment]
Hi, thank you for your response and guidance. I appreciate the suggestion to create a wrapper for bridging between MuJoCo and PyBullet. I'll explore this approach further. Thanks again!
